# Generated by Django 4.2.3 on 2023-12-16 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labcoat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryupdate',
            name='size',
            field=models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large'), ('XXL', 'Extra Extra Large')], max_length=20),
        ),
    ]
