# Generated by Django 4.0.6 on 2024-02-04 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labcoat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labcoatdistribution',
            name='date',
            field=models.DateField(),
        ),
    ]
