# Generated by Django 4.0.6 on 2024-02-18 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('labcoat', '0002_alter_labcoatdistribution_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventoryupdate',
            old_name='quantity_update',
            new_name='stock_change',
        ),
    ]
