# Generated by Django 4.0.6 on 2024-02-18 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labcoat', '0003_rename_quantity_update_inventoryupdate_stock_change'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InventoryUpdate',
        ),
        migrations.AddField(
            model_name='labcoatinventory',
            name='inventory_changes',
            field=models.JSONField(default=list),
        ),
    ]
