# Generated by Django 4.0.6 on 2024-02-18 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('labcoat', '0004_delete_inventoryupdate_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='labcoatinventory',
            old_name='inventory_changes',
            new_name='change_log',
        ),
    ]
