# Generated by Django 4.0.6 on 2024-02-19 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('labcoat', '0005_rename_inventory_changes_labcoatinventory_change_log'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labcoatinventory',
            name='total',
        ),
    ]
